package Jeopardy_Protocol;

import java.io.IOException;

/**
 */
public class ClientUI extends javax.swing.JFrame {

    TCP_Client client;
    int port = 44444;
    String host = "localhost";//Ömer Faruk Küçüker Proje Sonu: kullanıcı arayüzünü sadeleştirmek amacıyla bağlantıları arka plana aldık.

    /**
     * Creates new form ServerUI
     */
    public ClientUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConnect = new javax.swing.JButton();
        jButtonDisconnect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneHistory = new javax.swing.JTextPane();
        jLabelName = new javax.swing.JLabel();
        Abutton = new javax.swing.JButton();
        Bbutton = new javax.swing.JButton();
        Cbutton = new javax.swing.JButton();
        Dbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonConnect.setText("Connect");
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 24, 129, -1));

        jButtonDisconnect.setText("Disconnect");
        jButtonDisconnect.setEnabled(false);
        jButtonDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisconnectActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDisconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 24, 143, -1));

        jTextPaneHistory.setEditable(false);
        jScrollPane1.setViewportView(jTextPaneHistory);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, 444, 170));

        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("Client Name");
        getContentPane().add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 28, -1, -1));

        Abutton.setText("A");
        Abutton.setEnabled(false);
        Abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Abutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 245, 80, -1));

        Bbutton.setText("B");
        Bbutton.setEnabled(false);
        Bbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Bbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 245, 81, -1));

        Cbutton.setText("C");
        Cbutton.setEnabled(false);
        Cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Cbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 245, 81, -1));

        Dbutton.setText("D");
        Dbutton.setEnabled(false);
        Dbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Dbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 245, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("JeopardyProtocol\\back2.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 468, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
        try {//Ömer Faruk Küçüker
            //String host = jTextFieldIP.getText();
            //int port = Integer.parseInt(jTextFieldPort.getText());

            client = new TCP_Client();
            client.start(host, port, jTextPaneHistory, jLabelName, Abutton, Bbutton, Cbutton, Dbutton,jButtonDisconnect,jButtonConnect);

            disableConnectButton();
        } catch (IOException ex) {
            System.out.println("Error - jButtonConnectActionPerformed : " + ex);
            enableConnectButton();
        }
    }//GEN-LAST:event_jButtonConnectActionPerformed

    private void jButtonDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisconnectActionPerformed
        try {
            client.disconnect();
            enableConnectButton();
        } catch (IOException ex) {
            System.out.println("Error - jButtonDisconnectActionPerformed : " + ex);
        }
    }//GEN-LAST:event_jButtonDisconnectActionPerformed
    
    private void AbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbuttonActionPerformed
        try {   //Ömer Faruk Küçüker
            String message = Abutton.getText();

            if (!message.isEmpty()) {
                // String mesaj gönder
                client.sendMessage(message);
            }
        } catch (IOException ex) {
            System.out.println("Error - jButtonConnectActionPerformed : " + ex);
            enableConnectButton();
        }
    }//GEN-LAST:event_AbuttonActionPerformed

    private void BbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuttonActionPerformed
        try {//Ömer Faruk Küçüker
            String message = Bbutton.getText();

            if (!message.isEmpty()) {
                // String mesaj gönder
                client.sendMessage(message);
            }

            if (message.equals("son")) {
                jButtonDisconnectActionPerformed(evt);
            }
        } catch (IOException ex) {
            System.out.println("Error - jButtonConnectActionPerformed : " + ex);
            enableConnectButton();
        }
    }//GEN-LAST:event_BbuttonActionPerformed

    private void CbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbuttonActionPerformed
        try {//Ömer Faruk Küçüker
            String message = Cbutton.getText();

            if (!message.isEmpty()) {
                // String mesaj gönder
                client.sendMessage(message);
            }

            if (message.equals("son")) {
                jButtonDisconnectActionPerformed(evt);
            }
        } catch (IOException ex) {
            System.out.println("Error - jButtonConnectActionPerformed : " + ex);
            enableConnectButton();
        }
    }//GEN-LAST:event_CbuttonActionPerformed

    private void DbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DbuttonActionPerformed
        try {//Ömer Faruk Küçüker
            String message = Dbutton.getText();

            if (!message.isEmpty()) {
                // String mesaj gönder
                client.sendMessage(message);
            }

            if (message.equals("son")) {
                jButtonDisconnectActionPerformed(evt);
            }
        } catch (IOException ex) {
            System.out.println("Error - jButtonConnectActionPerformed : " + ex);
            enableConnectButton();
        }
    }//GEN-LAST:event_DbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ClientUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abutton;
    private javax.swing.JButton Bbutton;
    private javax.swing.JButton Cbutton;
    private javax.swing.JButton Dbutton;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDisconnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPaneHistory;
    // End of variables declaration//GEN-END:variables

    private void disableConnectButton() {
        jButtonConnect.setEnabled(false);
        jButtonDisconnect.setEnabled(true);
    }

    private void enableConnectButton() {
        jButtonConnect.setEnabled(true);
        jButtonDisconnect.setEnabled(false);
    }
}
